#!/usr/bin/env bash

set -e      # Exit immediately if any command fails

tests_dir="tests/tests-develop/VMTests/"
output_file="tests/templates/output-uiuck.txt"
expected_passing="tests/passing.expected"
now_passing="tests/passing.lastrun"

export cMODE=${cMODE:-VMTESTS}
export cSCHEDULE=${cSCHEDULE:-DEFAULT}

krun_with_opts() {
    krun --directory k/ --debug -cMODE=$cMODE -cSCHEDULE=$cSCHEDULE $@
}
export -f krun_with_opts

if krun --version | grep 'RV' >/dev/null 2>&1; then
    output_file="tests/templates/output-rvk.txt"
fi

progress() { echo "== $@"; }
success()  { echo -e "\e[32m== success: $@\e[0m";
             echo "$@" >> "$now_passing"
           }
failure()  { echo -e "\e[31m== failure: $@\e[0m"; }

list_tests()      { find "$tests_dir" -wholename "*$exp*" -name '*.json'; }
list_passing()    { cat "$expected_passing"; }
list_failing()    { list_tests | grep -Fvxf "$expected_passing" -; }
list_quicktests() { list_passing | sort -R | head -n 20; }

filter_codeship() {
    codeship_list="$1"
    case "$codeship_list" in
        1)  grep -e 'vmArithmeticTest/[a-dA-D]'                                                ;; # 05:08
        2)  grep -e 'vmArithmeticTest/expPowerOf256Of256'                                      ;; # ???
        3)  grep -e 'vmArithmeticTest/[eE]' | grep -v -e 'vmArithmeticTest/expPowerOf256Of256' ;; # ???
        4)  grep -e 'vmArithmeticTest/[f-mF-M]'                                                ;; # 08:19
        5)  grep -e 'vmArithmeticTest/[n-zN-Z]' -e 'vmBitwiseLogicOperationTest'               ;; # 11:39
        6)  grep -e 'vmBlockInfoTest' -e 'vmEnvironmentalInfoTest/[a-bA-B]'                    ;; # ???
        7)  grep -e 'vmEnvironmentalInfoTest/[cC]'                                             ;; # 11:25
        8)  grep -e 'vmEnvironmentalInfoTest/[d-zD-Z]' -e 'vmIOandFlowOperationsTest/[a-iA-B]' ;; # 04:22
        9)  grep -e 'vmIOandFlowOperationsTest/[C-I]'                                          ;; # ???
        10) grep -e 'vmIOandFlowOperationsTest/[j]'                                            ;; # ???
        11) grep -e 'vmIOandFlowOperationsTest/[J]'                                            ;; # ???
        13) grep -e 'vmIOandFlowOperationsTest/[k-mK-M]'                                       ;; # ???
        14) grep -e 'vmIOandFlowOperationsTest/[n-zN-Z]'                                       ;; # ???
        15) grep -e 'vmLogTest/log[0-2]' -e 'vmLogTest/log_'                                   ;; # ???
        16) grep -e 'vmLogTest/log[3-9]'                                                       ;; # ???
        17) grep -e 'vmPerformanceTest' -e 'vmPushDupSwapTest/[a-oA-O]'                        ;; # 06:34
        18) grep -e 'vmPushDupSwapTest/push[0-1]'                                              ;; # ???
        19) grep -e 'vmPushDupSwapTest/[q-zQ-Z]' -e 'vmPushDupSwapTest/push[2-9]'              ;; # ???
        20) grep -e 'vmSystemOperationsTest' -e 'vmSha3Test' -e 'vmtests'                      ;; # ???
    esac
}

pretty_diff() {
    if type colordiff >/dev/null 2>&1; then
        colordiff -u "$@"
    else
        diff -u "$@"
    fi
}

# Reads a list of json test files from stdin, and runs them
run_tests() {
    local test_file test_fail_count=0
    while read test_file; do
        let test_count="$test_count + 1"
        local output_differs=false
        progress "running: $test_file..."
        pretty_diff \
            --label expected <(cat "$output_file" | lint_krun) \
            --label actual   <(krun_with_opts "$test_file" | lint_krun) \
            || output_differs=true
        if $output_differs; then
            failure "$test_file"
            let test_fail_count="$test_fail_count + 1"
        else
            success "$test_file"
        fi
        progress "failed: $test_fail_count / $test_count"
    done
    return $test_fail_count
}

filter_tests() {
    local command=( exit 1 )
    case $# in
    0) cat;       return ;;
    1) grep "$1"; return ;;
    *) cat > /dev/null;
       echo >&2 "Too many expressions";
       ;;
    esac
}

run_ktest() {
    progress "running ktest ..."

    pushd k
    ktest ../tests/config.xml
    popd
}

lint_krun() {
    # Format, &gt; entity > and make each K task start on a new line
    xmllint -format - | sed -e 's/&gt;/>/g'  -e 's/~>/\n   ~>/g'
}

run_krun() {
    run_make all
    while read test_file; do
        progress "running: $test_file"
        krun_with_opts "$test_file" | lint_krun
    done
}

have_tangle=true
check_for_tangle() {
    type pandoc-tangle >/dev/null 2>&1  || {
        have_tangle=false
        echo -e >&2 "Warning: pandoc-tangle not installed."  \
                   "Ignoring changes in markdown files\n"
    }
}

check_for_tangle
run_make() {
    local make_opts=
    $have_tangle || make_opts="--assume-old ethereum.md --assume-old evm.md \
                               --assume-old data.md --assume-old krypto.md"
    make -s $make_opts $@
}

usage() {
    echo "
    usage:
       $0                       Build the definitions and kompile them
       $0 defn                  Only detangle the definitions

       $0 passing <regx>        Run known passing tests
       $0 failing <regx>        Run tests who's results we're not sure of
       $0 test    <regx>        Run passing and unknown tests

                                These tests are filtered by <regex>

       $0 quicktest             Run a quick round of a few tricky tests

       $0 list-tests   <regx>   Run passing and failing tests
       $0 list-failing <regx>   Run failing tests
       $0 list-passing <regx>   Run passing tests


       $0 krun <arg>            Same as test, but pretty print output instead of checking it
"
}

test_pipe_line() {
    local list=$1; shift
    local do_run=$1; shift;

    run_make all
    $list | filter_tests "$@" | $do_run; exit
}

run_debug() {
    run_make all
    file=$(test_pipe_line list_tests cat "$@" | head -n 1)
    progress "debugging: $file"
    krun_with_opts --debugger "$file"
    exit
}

run_codeship() {
    testset="$1"
    run_make all
    list_passing | filter_codeship "$testset" | run_tests; exit
}

[[ "$#" == '0' ]] && set build
run_command="$1" && shift
case "$run_command" in
    build)         run_make build ;;
    defn)          run_make defn ;;
    debug)         run_debug "$@" ;;
    krun)          test_pipe_line list_tests   run_krun  "$@" ;;
    test)          test_pipe_line list_tests   run_tests "$@" ;;
    passing)       test_pipe_line list_passing run_tests "$@" ;;
    failing)       test_pipe_line list_failing run_tests "$@" ;;
    codeship)      run_codeship $@ ;;
    quicktest)     list_quicktests | run_tests ;;
    list-tests)    test_pipe_line list_tests   cat       "$@" ;;
    list-passing)  test_pipe_line list_passing cat       "$@" ;;
    list-failing)  test_pipe_line list_failing cat       "$@" ;;
    list-codeship) list_passing | filter_codeship "$1" ;;
    ktest)         run_ktest ;;
    *)             usage; exit 1;;
esac
