#!/usr/bin/env sh

pandoc-tangle --from markdown --to code-k --code k world-state.md > k/world-state.k
pandoc-tangle --from markdown --to code-k --code k data.md        > k/data.k
pandoc-tangle --from markdown --to code-k --code k evm.md         > k/evm.k
pandoc-tangle --from markdown --to code-k --code k evm-dasm.md    > k/evm-dasm.k
pandoc-tangle --from markdown --to code-k --code k ethereum.md    > k/ethereum.k

pushd k
kompile --debug --main-module ETHEREUM --syntax-module ETHEREUM ethereum.k
popd
