#!/usr/bin/env sh

pandoc-tangle --from markdown --to code-k --code k words.md       > k/words.k
pandoc-tangle --from markdown --to code-k --code k opcodes.md     > k/opcodes.k
pandoc-tangle --from markdown --to code-k --code k gas.md         > k/gas.k
pandoc-tangle --from markdown --to code-k --code k world-state.md > k/world-state.k
pandoc-tangle --from markdown --to code-k --code k evm.md         > k/evm.k

pushd k
kompile --debug evm.k
popd
