#!/usr/bin/env bash 

desugar_get_jq() {
    if [[ ! -f jq ]]; then
        jqurl="https://github.com/stedolan/jq/releases/download/jq-1.5/"
        if [[ "$OSTYPE" == "linux-gnu" ]]; then
            binary="jq-linux64"
            checksum="c6b3a7d7d3e7b70c6f51b706a3b90bd01833846c54d32ca32f0027f00226ff6d"
        elif [[ "$OSTYPE" == "darwin"* ]]; then
            binary="jq-osx-amd64"
            checksum="386e92c982a56fe4851468d7a931dfca29560cee306a0e66c6a1bd4065d3dac5"
        fi

        curl -OL "$jqurl$binary"

        dchecksum=$(shasum -a 256 $binary | awk '{print $1}')

        if [[ ! "$checksum" == "$dchecksum" ]]; then
            >&2 echo "checksums don't match"
            rm "$binary"
            exit 1
        fi
        mv "$binary" jq 
        chmod +x jq
    fi
}

desugar_process_json() {
    echo "processing json ..."
    echo "==================================="
    for jsonfile in `find . -name "*.json"`; do
        dirname=`dirname "$jsonfile"`
        filename=`basename "$jsonfile" .json`
        directory="$dirname/$filename"
        if [[ ! -d "$directory" ]]; then
            mkdir "$directory" 
        fi

        metafile="$directory/$filename".meta
        cat "$jsonfile" | ./jq 'to_entries | map_values({filename:(.key) , contents: {(.key): (.value)}}) ' > "$metafile"
        ./testgen.py "$metafile" `pwd`/templates/output.txt

        rm "$metafile"
        cp templates/config.xml "$directory"
    done
    echo "done"
    echo "==================================="
}

#Temporary
desugar_cleanup() {
    echo "cleaning up ..."
    echo "==================================="
    cd tests-develop && ls | grep -v "VMTests" | xargs rm -r
    cd "VMTests" && ls | grep -v "vmArithmeticTest.json" | xargs rm -rf
    cd ../../
}

[[ "$#" == '0' ]] && set all

while [[ "$#" -gt '0' ]]; do
    desugar_command="$1" && shift
    case "$desugar_command" in
        all)      set clean getjq process ;;
        clean)    desugar_cleanup ;;
        getjq)    desugar_get_jq ;;
        process)  desugar_process_json ;;
        *)        echo "Unrecognized option: '$tangle_command' ..." ;;
    esac
done

