#!/usr/bin/env bash

desugar_process_json() {
    echo "processing json ..."
    echo "==================================="
    for jsonfile in `find . -name "*.json"`; do
        dirname=`dirname "$jsonfile"`
        filename=`basename "$jsonfile" .json`

        mkdir "$dirname/$filename"
    done
    echo "done"
    echo "==================================="
}

#Temporary
desugar_cleanup() {
    echo "cleaning up ..."
    echo "==================================="
    cd tests-develop && ls | grep -v "VMTests" | xargs rm -r
    cd "VMTests" && ls | grep -v ".*\.json" | rm -rf
}

[[ "$#" == '0' ]] && set all

while [[ "$#" -gt '0' ]]; do
    desugar_command="$1" && shift
    case "$desugar_command" in
        all)      set clean process ;;
        clean)    desugar_cleanup ;;
        process)  desugar_process_json ;;
        *)        echo "Unrecognized option: '$tangle_command' ..." ;;
    esac
done

