tests/ethereum-tests/VMTests/vmEnvironmentalInfo/calldatacopy_DataIndexTooHigh2.json
tests/ethereum-tests/VMTests/vmEnvironmentalInfo/calldatacopy_DataIndexTooHigh2_return.json
tests/ethereum-tests/VMTests/vmEnvironmentalInfo/calldatacopy_DataIndexTooHigh.json
tests/ethereum-tests/VMTests/vmEnvironmentalInfo/calldatacopy_DataIndexTooHigh_return.json
tests/ethereum-tests/VMTests/vmEnvironmentalInfo/calldataload_BigOffset.json
tests/ethereum-tests/VMTests/vmEnvironmentalInfo/calldataloadSizeTooHigh.json
tests/ethereum-tests/VMTests/vmEnvironmentalInfo/codecopy_DataIndexTooHigh.json
tests/specs/functional/merkle-failing-spec.k
