tests/specs/benchmarks/address00-spec.k
tests/specs/benchmarks/ecrecover00-siginvalid-spec.k
tests/specs/benchmarks/ecrecover00-sigvalid-spec.k
tests/specs/benchmarks/ecrecoverloop00-sig0-invalid-spec.k
tests/specs/benchmarks/encode-keccak00-spec.k
tests/specs/benchmarks/encodepacked-keccak01-spec.k
tests/specs/benchmarks/functional-spec.k
tests/specs/benchmarks/keccak00-spec.k
tests/specs/benchmarks/overflow00-nooverflow-spec.k
tests/specs/benchmarks/overflow00-overflow-spec.k
tests/specs/benchmarks/requires01-a0gt0-spec.k
tests/specs/benchmarks/requires01-a0le0-spec.k
tests/specs/benchmarks/staticarray00-spec.k
tests/specs/benchmarks/staticloop00-a0lt10-spec.k
tests/specs/benchmarks/storagevar00-spec.k
tests/specs/benchmarks/storagevar01-spec.k
tests/specs/benchmarks/storagevar02-nooverflow-spec.k
tests/specs/benchmarks/storagevar02-overflow-spec.k
tests/specs/benchmarks/storagevar03-spec.k
tests/specs/bihu/forwardToHotWallet-failure-1-spec.k
tests/specs/bihu/forwardToHotWallet-failure-2-spec.k
tests/specs/bihu/forwardToHotWallet-failure-3-spec.k
tests/specs/bihu/forwardToHotWallet-failure-4-spec.k
tests/specs/bihu/functional-spec.k
tests/specs/erc20/ds/allowance-spec.k
tests/specs/erc20/ds/approve-failure-spec.k
tests/specs/erc20/ds/approve-success-spec.k
tests/specs/erc20/ds/balanceOf-spec.k
tests/specs/erc20/ds/totalSupply-spec.k
tests/specs/erc20/ds/transfer-failure-1-a-spec.k
tests/specs/erc20/ds/transfer-failure-1-c-spec.k
tests/specs/erc20/ds/transfer-failure-2-a-spec.k
tests/specs/erc20/ds/transfer-failure-2-b-spec.k
tests/specs/erc20/ds/transferFrom-failure-1-d-spec.k
tests/specs/erc20/ds/transferFrom-failure-2-a-spec.k
tests/specs/erc20/ds/transferFrom-failure-2-c-spec.k
tests/specs/erc20/ds/transfer-success-2-spec.k
tests/specs/erc20/hkg/allowance-spec.k
tests/specs/erc20/hkg/approve-spec.k
tests/specs/erc20/hkg/balanceOf-spec.k
tests/specs/erc20/hkg/totalSupply-spec.k
tests/specs/erc20/hkg/transfer-failure-1-spec.k
tests/specs/erc20/hkg/transfer-failure-2-spec.k
tests/specs/erc20/hkg/transferFrom-failure-1-spec.k
tests/specs/erc20/hkg/transferFrom-failure-2-spec.k
tests/specs/erc20/hkg/transferFrom-success-2-spec.k
tests/specs/erc20/hkg/transfer-success-1-spec.k
tests/specs/erc20/hkg/transfer-success-2-spec.k
tests/specs/examples/erc20-spec.md
tests/specs/examples/erc721-spec.md
tests/specs/examples/solidity-code-spec.md
tests/specs/examples/storage-spec.md
tests/specs/examples/sum-to-n-spec.k
tests/specs/functional/infinite-gas-spec.k
tests/specs/functional/infinite-gas-spec.k
tests/specs/functional/lemmas-no-smt-spec.k
tests/specs/functional/lemmas-spec.k
tests/specs/functional/merkle-spec.k
tests/specs/functional/merkle-spec.k
tests/specs/functional/storageRoot-spec.k
tests/specs/functional/storageRoot-spec.k
tests/specs/mcd/cat-exhaustiveness-spec.k
tests/specs/mcd/cat-file-addr-pass-rough-spec.k
tests/specs/mcd/dai-adduu-fail-rough-spec.k
tests/specs/mcd/dai-symbol-pass-spec.k
tests/specs/mcd/dstoken-approve-fail-rough-spec.k
tests/specs/mcd/dsvalue-peek-pass-rough-spec.k
tests/specs/mcd/dsvalue-read-pass-spec.k
tests/specs/mcd/dsvalue-read-pass-summarize-spec.k
tests/specs/mcd/end-subuu-pass-spec.k
tests/specs/mcd/flipper-addu48u48-fail-rough-spec.k
tests/specs/mcd/flipper-tau-pass-spec.k
tests/specs/mcd/flipper-ttl-pass-spec.k
tests/specs/mcd/flopper-cage-pass-spec.k
tests/specs/mcd/functional-spec.k
tests/specs/mcd/vat-addui-fail-rough-spec.k
tests/specs/mcd/vat-deny-diff-fail-rough-spec.k
tests/specs/mcd/vat-move-diff-rough-spec.k
tests/specs/mcd/vat-mului-pass-spec.k
tests/specs/mcd/vat-subui-fail-rough-spec.k
tests/specs/mcd/vat-subui-pass-rough-spec.k
tests/specs/mcd/vat-subui-pass-spec.k
tests/specs/mcd/vow-fess-fail-rough-spec.k
tests/specs/mcd/vow-flog-fail-rough-spec.k
tests/specs/opcodes/evm-optimizations-spec.md
tests/specs/opcodes/evm-optimizations-spec.md
