#!/usr/bin/env bash

set -xeuo pipefail

distro="${1:-jammy}"

case "$distro" in
    jammy)  control_file=control.jammy              ;;
    *)      echo "Unknown distro: $distro" ; exti 1 ;;
esac

rm -rf debian

cp -r package/debian ./debian
mv debian/$control_file debian/control
dpkg-buildpackage --no-sign
