requires "lemmas/lemmas.k"

requires "dai-bin-runtime.k"
requires "daijoin-bin-runtime.k"
requires "gemjoin-bin-runtime.k"
requires "jug-bin-runtime.k"
requires "pot-bin-runtime.k"
requires "spotter-bin-runtime.k"
requires "vat-bin-runtime.k"

module MCD-VERIFICATION
    imports LEMMAS

    imports DAI-BIN-RUNTIME
    imports DAIJOIN-BIN-RUNTIME
    imports GEMJOIN-BIN-RUNTIME
    imports JUG-BIN-RUNTIME
    imports POT-BIN-RUNTIME
    imports SPOTTER-BIN-RUNTIME
    imports VAT-BIN-RUNTIME

endmodule
