requires "flopper-arithmetic-spec.k"
requires "flopper-cage-pass-spec.k"
requires "flopper-dent-guy-diff-tic-not-0-pass-rough-spec.k"
requires "flopper-dent-guy-same-pass-rough-spec.k"
requires "flopper-file-pass-rough-spec.k"
requires "flopper-kick-pass-rough-spec.k"
requires "flopper-tick-pass-rough-spec.k"

module FLOPPER-SPEC
    imports FLOPPER-ARITHMETIC-SPEC
    imports FLOPPER-CAGE-PASS-SPEC
    imports FLOPPER-DENT-GUY-DIFF-TIC-NOT-0-PASS-ROUGH-SPEC
    imports FLOPPER-DENT-GUY-SAME-PASS-ROUGH-SPEC
    imports FLOPPER-FILE-PASS-ROUGH-SPEC
    imports FLOPPER-KICK-PASS-ROUGH-SPEC
    imports FLOPPER-TICK-PASS-ROUGH-SPEC
endmodule
