requires "vat-addui-fail-rough-spec.k"
requires "vat-arithmetic-spec.k"
requires "vat-deny-diff-fail-rough-spec.k"
requires "vat-flux-diff-pass-rough-spec.k"
requires "vat-fold-pass-rough-spec.k"
requires "vat-fork-diff-pass-rough-spec.k"
requires "vat-frob-diff-zero-dart-pass-rough-spec.k"
requires "vat-move-diff-rough-spec.k"
requires "vat-slip-pass-rough-spec.k"
requires "vat-subui-fail-rough-spec.k"

module VAT-SPEC
    imports VAT-ADDUI-FAIL-ROUGH-SPEC
    imports VAT-ARITHMETIC-SPEC
    imports VAT-DENY-DIFF-FAIL-ROUGH-SPEC
    imports VAT-FLUX-DIFF-PASS-ROUGH-SPEC
    imports VAT-FOLD-PASS-ROUGH-SPEC
    imports VAT-FORK-DIFF-PASS-ROUGH-SPEC
    imports VAT-FROB-DIFF-ZERO-DART-PASS-ROUGH-SPEC
    imports VAT-MOVE-DIFF-ROUGH-SPEC
    imports VAT-SLIP-PASS-ROUGH-SPEC
    imports VAT-SUBUI-FAIL-ROUGH-SPEC
endmodule
