requires "vow-arithmetic-spec.k"
requires "vow-cage-deficit-pass-rough-spec.k"
requires "vow-cage-surplus-pass-rough-spec.k"
requires "vow-fess-fail-rough-spec.k"
requires "vow-flog-fail-rough-spec.k"

module VOW-SPEC
    imports VOW-ARITHMETIC-SPEC
    imports VOW-CAGE-DEFICIT-PASS-ROUGH-SPEC
    imports VOW-CAGE-SURPLUS-PASS-ROUGH-SPEC
    imports VOW-FESS-FAIL-ROUGH-SPEC
    imports VOW-FLOG-FAIL-ROUGH-SPEC
endmodule
