#!/usr/bin/env sh

pandoc-tangle --from markdown --to code-k --code k evm-data.md      > evm-data.k
pandoc-tangle --from markdown --to code-k --code k evm-syntax.md    > evm-syntax.k
pandoc-tangle --from markdown --to code-k --code k evm-semantics.md > evm-semantics.k

# kompile --debug --main-module EVM-OPCODE evm-data.k
# kompile --debug --main-module EVM-SYNTAX evm-syntax.k
kompile --debug --main-module EVM evm-semantics.k
