name: 'With Docker'
description: 'Run a given stage with Docker Image'
inputs:
  tag:
    description: 'Docker image tag to use'
    required: true
runs:
  using: 'composite'
  steps:
  - name: 'Set up Docker'
    shell: bash {0}
    env:
      TAG_NAME: ${{ inputs.tag }}
    run: |
      set -euxo pipefail

      Z3_VERSION=4.8.15
      K_COMMIT=$(cut -c 2- deps/k_release)

      docker build . --file .github/workflows/Dockerfile.z3 \
        --tag z3:${Z3_VERSION}

      docker build . --file .github/workflows/Dockerfile           \
        --tag runtimeverification/${TAG_NAME}                      \
        --build-arg K_COMMIT=${K_COMMIT}                           \
        --build-arg Z3_VERSION=${Z3_VERSION}                       \

      docker run                        \
        --name ${TAG_NAME}              \
        --rm                            \
        --interactive                   \
        --tty                           \
        --detach                        \
        --user root                     \
        --workdir /home/user            \
        runtimeverification/${TAG_NAME}

      docker cp . ${TAG_NAME}:/home/user
      docker exec ${TAG_NAME} chown -R user:user /home/user
