FROM archlinux/base

RUN    pacman -Syu --noconfirm \
    && pacman -S   --noconfirm base base-devel curl gcc git hub make net-tools nodejs npm python2 sudo

RUN npm install -g npx

ARG USER_ID=1000
ARG GROUP_ID=1000
RUN    groupadd -g $GROUP_ID user                                                \
    && useradd --create-home --uid $USER_ID --shell /bin/sh --gid $GROUP_ID user \
    && echo "user ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers
